//src/lib/category-themes
export const CATEGORY_THEMES = {
  all: {
    id: "all",
    label: "All",
    icon: "/icons/all.svg",
    logo: "/logo.svg",
    primary: "#F97316",
    primaryHover: "#EA580C",
    primaryLight: "#F9731618",
    bg: "#FFF7ED",
    border: "#FDBA74",
    textColor: "#9A3412",
  },
  gadgets: {
    id: "gadgets",
    label: "Gadgets",
    icon: "/icons/gadgets.svg",
    logo: "/logogadget.svg",
    primary: "#7C3AED",
    primaryHover: "#6D28D9",
    primaryLight: "#7C3AED18",
    bg: "#F5F3FF",
    border: "#DDD6FE",
    textColor: "#5B21B6",
  },
  solar: {
    id: "solar",
    label: "Solar",
    icon: "/icons/solar.svg",
    logo: "/logosolar.svg",
    primary: "#16A34A",
    primaryHover: "#15803D",
    primaryLight: "#16A34A18",
    bg: "#F0FDF4",
    border: "#BBF7D0",
    textColor: "#14532D",
  },
  electronics: {
    id: "electronics",
    label: "Electronics",
    icon: "/icons/electronics.svg",
    logo: "/logoelectronics.svg",
    primary: "#0284C7",
    primaryHover: "#0369A1",
    primaryLight: "#0284C718",
    bg: "#F0F9FF",
    border: "#BAE6FD",
    textColor: "#0C4A6E",
  },
  phones: {
    id: "phones",
    label: "Phones",
    icon: "/icons/phones.svg",
    logo: "/logophones.svg",
    primary: "#2563EB",
    primaryHover: "#1D4ED8",
    primaryLight: "#2563EB18",
    bg: "#EFF6FF",
    border: "#BFDBFE",
    textColor: "#1E3A8A",
  },
  computers: {
    id: "computers",
    label: "Computers",
    icon: "/icons/computers.svg",
    logo: "/logocomputer.svg",
    primary: "#0F766E",
    primaryHover: "#115E59",
    primaryLight: "#0F766E18",
    bg: "#F0FDFA",
    border: "#99F6E4",
    textColor: "#134E4A",
  },
  machinery: {
    id: "machinery",
    label: "Machinery",
    icon: "/icons/machinery.svg",
    logo: "/logomachinery.svg",
    primary: "#D97706",
    primaryHover: "#B45309",
    primaryLight: "#D9770618",
    bg: "#FFFBEB",
    border: "#FCD34D",
    textColor: "#92400E",
  },
} as const

export type CategoryId = keyof typeof CATEGORY_THEMES
export type ProductCategoryId = Exclude<CategoryId, "all">